platform :ios, '10.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'markerExample' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  # pre_install do |installer|
  #   codegen_pre_install(installer)
  # end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
  # pod 'RNImageMarker', :path => '../node_modules/react-native-image-marker/RNImageMarker.local.podspec'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end

