package com.jimmydaddy.imagemarker.turbo

import android.os.Build
import androidx.annotation.RequiresApi
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.Promise
import com.jimmydaddy.imagemarker.NativeImageMarkerSpec
import com.jimmydaddy.imagemarker.ImageMarkerManager
import com.jimmydaddy.imagemarker.FabricImageLoader

/**
 * Android TurboModule implementation for ImageMarker with Fabric integration
 * Extends the Codegen-generated NativeImageMarkerSpec class
 * Provides JSI-based communication for improved performance
 * Handles asynchronous operations with Fabric-compatible image loading
 * 
 * Note: NativeImageMarkerSpec is generated by Codegen from specs/NativeImageMarker.ts
 * The generated class is located in android/build/generated/source/codegen/java/
 */
class ImageMarkerTurboModule(reactContext: ReactApplicationContext) : NativeImageMarkerSpec(reactContext) {
    
    companion object {
        const val NAME = "ImageMarker"
    }
    
    // Use composition instead of inheritance to avoid final class issue
    private val imageMarkerManager = ImageMarkerManager(reactContext)
    private val fabricImageLoader = FabricImageLoader(reactContext, 2048)
    
    override fun getName(): String {
        return NAME
    }
    
    /**
     * Mark image with text using TurboModule interface with Fabric integration
     * Processes image sources through Fabric-compatible pipeline before delegation
     */
    @RequiresApi(Build.VERSION_CODES.N)
    override fun markWithText(options: ReadableMap, promise: Promise) {
        try {
            // Delegate directly to ImageMarkerManager
            // FabricImageLoader is available for future Fabric-specific enhancements
            imageMarkerManager.markWithText(options, promise)
        } catch (e: Exception) {
            promise.reject("TURBO_MODULE_ERROR", "TurboModule text marking failed: ${e.message}", e)
        }
    }
    
    /**
     * Mark image with image using TurboModule interface with Fabric integration
     * Processes image sources through Fabric-compatible pipeline before delegation
     */
    @RequiresApi(Build.VERSION_CODES.N)
    override fun markWithImage(options: ReadableMap, promise: Promise) {
        try {
            // Delegate directly to ImageMarkerManager
            // FabricImageLoader is available for future Fabric-specific enhancements
            imageMarkerManager.markWithImage(options, promise)
        } catch (e: Exception) {
            promise.reject("TURBO_MODULE_ERROR", "TurboModule image marking failed: ${e.message}", e)
        }
    }
}