export { ImageMarkerEditorController } from './controller';
export {
  angle,
  distance,
  normalizeSafeArea,
  snapLayerPosition,
} from './geometry';
export {
  createEditorViewportProjection,
  fitEditorSizeWithinMax,
  projectEditorPoint,
  projectEditorRecipe,
  unprojectEditorPoint,
  type EditorViewportProjection,
} from './projection';
export {
  createBrandLogoLayer,
  createBrandTextLayer,
  createEditorBrandKit,
  createEditorTemplate,
  materializeEditorTemplate,
} from './presets';
export type {
  EditorAlignment,
  EditorAsset,
  EditorAutosaveOptions,
  EditorBrandKit,
  EditorClipboardDocument,
  EditorContentCredentialsExport,
  EditorDistribution,
  EditorExportOptions,
  EditorExportResult,
  EditorInvisibleExport,
  EditorKeyCommand,
  EditorLayerBounds,
  EditorPoint,
  EditorRect,
  EditorRenderRequest,
  EditorSafeArea,
  EditorSelectionMode,
  EditorSerializedState,
  EditorSize,
  EditorSnapContext,
  EditorSnapGuide,
  EditorState,
  EditorTemplate,
  EditorTextLayerPatch,
  EditorViewportState,
  ImageMarkerEditorControllerOptions,
  ImageMarkerEditorRenderAdapter,
  MarkerImageInfo,
  WatermarkBlendMode,
  WatermarkRecipeDefinition,
  WatermarkRecipeDefinitionLayer,
  WatermarkRecipeDocument,
  WatermarkRecipeInput,
  WatermarkTextStyle,
} from './types';
