#!/bin/bash

# iOS CI Setup Script
# Ensures proper environment configuration for iOS builds in CI

set -e

echo "🍎 Setting up iOS CI environment..."

# Get the example app directory from argument or default to example-0.73
EXAMPLE_APP=${1:-example-0.73}
IOS_DIR="${EXAMPLE_APP}/ios"

if [ ! -d "$IOS_DIR" ]; then
    echo "❌ iOS directory not found: $IOS_DIR"
    exit 1
fi

cd "$IOS_DIR"

echo "📍 Working directory: $(pwd)"

# 1. Configure Node.js path for Xcode
echo "🔧 Configuring Node.js path for Xcode..."
NODE_PATH=$(command -v node)
echo "Node.js found at: $NODE_PATH"

# Create or update .xcode.env.local with dynamic node detection
cat > .xcode.env.local << EOF
# Auto-generated by iOS CI setup
# Dynamic Node.js detection for CI compatibility
export NODE_BINARY=\$(command -v node)

# Architecture configuration
export RCT_NEW_ARCH_ENABLED=\${RCT_NEW_ARCH_ENABLED:-0}

# Hermes configuration
export USE_HERMES=\${USE_HERMES:-1}
EOF

echo "✅ Created .xcode.env.local:"
cat .xcode.env.local

# 2. Verify CocoaPods installation
echo "🔧 Verifying CocoaPods installation..."
if ! command -v pod &> /dev/null; then
    echo "❌ CocoaPods not found"
    exit 1
fi

POD_VERSION=$(pod --version)
echo "✅ CocoaPods version: $POD_VERSION"

# 3. Clean previous builds and caches
echo "🧹 Cleaning previous builds and caches..."
rm -rf build DerivedData
rm -rf Pods Podfile.lock

# 4. Clear CocoaPods cache
echo "🧹 Clearing CocoaPods cache..."
pod cache clean --all

# 5. Install dependencies with verbose output
echo "📦 Installing CocoaPods dependencies..."
if [ "$RCT_NEW_ARCH_ENABLED" = "1" ]; then
    echo "🏗️ Installing with New Architecture enabled"
    RCT_NEW_ARCH_ENABLED=1 pod install --repo-update --verbose
else
    echo "🏗️ Installing with Legacy Architecture"
    RCT_NEW_ARCH_ENABLED=0 pod install --repo-update --verbose
fi

# 6. Verify installation
echo "✅ Verifying installation..."
if [ -d "Pods" ] && [ -f "Podfile.lock" ]; then
    echo "✅ CocoaPods installation successful"
    echo "📊 Installed pods:"
    ls -la Pods/ | head -10
else
    echo "❌ CocoaPods installation failed"
    exit 1
fi

# 7. Check Xcode workspace
WORKSPACE_FILE=$(find . -name "*.xcworkspace" | head -1)
if [ -n "$WORKSPACE_FILE" ]; then
    echo "✅ Xcode workspace found: $WORKSPACE_FILE"
else
    echo "❌ Xcode workspace not found"
    exit 1
fi

# 8. Validate build configuration
echo "🔍 Validating build configuration..."
if [ "$RCT_NEW_ARCH_ENABLED" = "1" ]; then
    echo "🏗️ New Architecture configuration:"
    echo "  - RCT_NEW_ARCH_ENABLED=1"
    echo "  - TurboModules: Enabled"
    echo "  - Fabric: Enabled"
else
    echo "🏗️ Legacy Architecture configuration:"
    echo "  - RCT_NEW_ARCH_ENABLED=0"
    echo "  - Bridge: Enabled"
fi

echo "✅ iOS CI setup completed successfully!"
echo "🚀 Ready for build and test"